export const Users = [
  {
    id: 1,
    profilePicture: "Portrait.jpg",
    username: "Lindi",
  },
  {
    id: 2,
    profilePicture: "Portrait2.jpg",
    username: "Jane",
  },
  {
    id: 3,
    profilePicture: "Portrait3.jpeg",
    username: "Mary",
  },
  {
    id: 4,
    profilePicture: "Portrait4.jpeg",
    username: "Belle",
  },
];

export const Posts = [
  {
    id: 1,
    title: "Bangkok trip",
    ingredients: "thai food",
    desc: "nice photo",
    difficulty: "super",
    duration: "5min",
    photo: "post/1.jpg",
    currentDate: "12 Dec 2022",
    userId: 1,
    like: 30,
    comment: 10,
  },
  {
    id: 2,
    title: "",
    desc: "abc",
    difficulty: "abc",
    duration: "abc",
    photo: "post/2.jpg",
    currentDate: "12 Dec 2022",
    userId: 2,
    like: 31,
    comment: 11,
  },
  {
    id: 3,
    title: "",
    desc: "abc",
    difficulty: "abc",
    duration: "abc",
    photo: "post/3.jpg",
    currentDate: "12 Dec 2022",
    userId: 3,
    like: 32,
    comment: 12,
  },
  {
    id: 4,
    title: "",
    desc: "abc",
    difficulty: "abc",
    duration: "abc",
    photo: "post/4.jpg",
    currentDate: "12 Dec 2022",
    userId: 4,
    like: 33,
    comment: 13,
  },
];
